# Generated by Django 4.2.30 on 2026-04-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpansionPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_code', models.CharField(blank=True, max_length=50, verbose_name='시리얼코드')),
                ('name', models.CharField(max_length=200, verbose_name='확장팩명')),
                ('price1', models.IntegerField(default=0, verbose_name='가격1 (낱개)')),
                ('price2', models.IntegerField(default=0, verbose_name='가격2 (박스)')),
                ('quantity', models.IntegerField(default=0, verbose_name='수량')),
                ('img_src', models.URLField(blank=True, max_length=500, verbose_name='이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expansion_packs',
                'ordering': ['id'],
            },
        ),
    ]
