# Generated by Django 4.2.30 on 2026-04-29 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expansionpack',
            name='quantity',
        ),
        migrations.AddField(
            model_name='expansionpack',
            name='qty_bonbu',
            field=models.IntegerField(default=0, verbose_name='재고 (본부)'),
        ),
        migrations.AddField(
            model_name='expansionpack',
            name='qty_busan',
            field=models.IntegerField(default=0, verbose_name='재고 (부산)'),
        ),
        migrations.AddField(
            model_name='expansionpack',
            name='qty_gwangju',
            field=models.IntegerField(default=0, verbose_name='재고 (광주)'),
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', '입고'), ('remove', '출고'), ('transfer', '이동')], max_length=10, verbose_name='작업')),
                ('location', models.CharField(blank=True, choices=[('gwangju', '광주'), ('busan', '부산'), ('bonbu', '본부')], max_length=10, verbose_name='위치')),
                ('from_location', models.CharField(blank=True, choices=[('gwangju', '광주'), ('busan', '부산'), ('bonbu', '본부')], max_length=10, verbose_name='출발지')),
                ('to_location', models.CharField(blank=True, choices=[('gwangju', '광주'), ('busan', '부산'), ('bonbu', '본부')], max_length=10, verbose_name='도착지')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cards.expansionpack', verbose_name='확장팩')),
            ],
            options={
                'db_table': 'inventory_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
