# Generated by Django 4.2.30 on 2026-04-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_expansionpack_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000, verbose_name='이미지 URL')),
                ('location', models.CharField(choices=[('gwangju', '광주'), ('busan', '부산'), ('bonbu', '본부')], max_length=10, verbose_name='위치')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
            ],
            options={
                'db_table': 'photo_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
