# Generated by Django 4.2.30 on 2026-04-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_photorecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='photorecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시'),
        ),
    ]
